#!/usr/bin/env bash
#Prints fizzbuzz for divisible by 3 and 5, fizz for div by 5 and buzz for 3

i=1
while [[ $i -lt 101 ]]
do
    if (( i % 3 == 0 && i % 5 == 0 ));then
        echo "FizzBuzz"
    elif (( i % 3 == 0 ));then
        echo "Fizz"
    elif (( i % 5 == 0 ));then
        echo "Buzz"
    else
        echo $i
    fi
    ((i++))
done
