#!/usr/bin/env bash
# This script displays best school 10 times, with a condition that on the 9th iteration, it will display "Hi" instead of "Best School"
i=0
until [ $i -eq 11 ]
do 
    if [ $i -eq 9 ]
    then 
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done