#!/usr/bin/env bash
# Displays bad luck in 4, good luck in 8 and Best School in other iterations
i=0
while [ $i -lt 10 ]
do 
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then 
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done