#!/usr/bin/env bash
# Prints superstitious numbers from 1 to 20
# If 4, bad luck from China, 8, Japan, and 17 Italy

i=1
while [ $i -lt 21 ]; do
	case $i in
		4)
			echo -e "4\nbad luck from China"
			;;
		8)
			echo -e "8\nbad luck from Japan"
			;;
		17)
			echo -e "17\nbad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done