#!/usr/bin/env bash
# Prints supersitious numbers from 1 to 20
# If 4, bad luck from china, 8, japan, and 18 Italy
i=1
while [ $i -lt 21 ]
do
    if [ $i -eq 4 ]
    then
        echo -e "4 \nbad luck from China"
    elif [ $i -eq 8 ]
    then
        echo -e "8 \nbad luck from Japan"
    elif [ $i -eq 17 ]
    then 
        echo -e "17 \nbad luck from Italy"
    else
        echo "$i"
    fi
    ((i++))
done